sudo: required
services:
    - docker

# NOTE: We are aonly demonstrating test for the react client application
# We could add similar steps for other projects
before_install:
    - docker build -t samuelsegal/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true samuelsegal/react-test yarn test

after_success:
    # Build images
    - docker build -t samuelsegal/multi-client ./client
    - docker build -t samuelsegal/multi-nginx ./nginx
    - docker build -t samuelsegal/multi-server ./server
    - docker build -t samuelsegal/multi-worker ./worker
    # Login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take All Images and push to docker hub
    - docker push samuelsegal/multi-client
    - docker push samuelsegal/multi-nginx
    - docker push samuelsegal/multi-server
    - docker push samuelsegal/multi-worker

deploy:
    provider: elasticbeanstalk
    edge: true
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-316922790688
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
